### ISSUE TITLE
Crear estructura

### ISSUE THREAD

**Issue by Daniela-RL** [FundacioEsplaiJava2024/ToDoList-grupo-1#10]
Lista de componentes que se tienen que crear (vacíos) para el layout:

Título: contendrá un string con el título del proyecto
Project wrapper: ocupa el resto del espacio y es donde se van a mostrar los botones (filtro + add) y la lista.

![Image](https://github.com/FundacioEsplaiJava2024/ToDoList-grupo-1/assets/82368852/8049c0a5-f8fd-4ff5-9219-94ffd486ebd6)

**Comment by AngelCorral0** [comment]
Estructurar el proyecto para tener una idea de como queremos que se vea 

![Image](https://github.com/FundacioEsplaiJava2024/ToDoList-grupo-1/assets/121192814/f3189468-d7f5-4a68-baae-4f1a901f3566)

**Comment by SaraVictorFernandez** [comment]
Lista de componentes que se tienen que crear (vacíos) para el layout:

- Título: contendrá un string con el título del proyecto
- Project wrapper: ocupa el resto del espacio y es donde se van a mostrar los botones (filtro + add) y la lista
