### ISSUE TITLE
Crear tareas

### ISSUE THREAD

**Issue by Daniela-RL** [FundacioEsplaiJava2024/ToDoList-grupo-1#9]
El objetivo es "ser capaz de crear una tarea". Esto incluye:

- Mostrar botón de añadir tarea y gestionar el click (en el button wrapper)
- Mostrar popup, que cogerá los datos de la nueva tarea y se los pasará al button wrapper

**Comment by SaraVictorFernandez** [comment]
Añado info para mejorar la descripción.

El objetivo es "ser capaz de crear una tarea". Esto incluye:
- Mostrar botón de añadir tarea y gestionar el click (en el button wrapper)
- Mostrar popup, que cogerá los datos de la nueva tarea y se los pasará al button wrapper
- Pasar los datos de la nueva tarea al componente Proyecto
- Guardar la nueva tarea en la lista de tareas (dentro de Proyecto, que es el componente que las guarda)

@Daniela-RL , @Davidvamosfull , @rvst312 , @AngelCorral0 . Revisad esta y las demás tareas, que tengan una descripción completa que indique todos los requisitos de la tarea.
